### ISSUE TITLE
Access Issue to Private Repositories

### ISSUE THREAD

**Issue by LI-Mingyu** [Photenix-AI/plugins#2]
It appears that our private GitHub repositories are denying access from our development tool, despite the fact that the account associated with the `GITHUB_TOKEN` has been added to the repositories.

**Comment by DevBuddyConnor** [comment]
test

**Comment by ClawDevin** [comment]
**问题分析与解决建议**:

根据提供的描述，您在尝试从开发工具访问私有GitHub仓库时遇到了权限问题，尽管与`GITHUB_TOKEN`相关联的账户已经被添加到私有仓库。

**建议如下**:
1. **确认Token权限**：请确保`GITHUB_TOKEN`具有足够的权限可以访问私有仓库，尤其是`repo`作用域。

2. **检查仓库访问设置**：在GitHub仓库的“Settings”->“Manage access”中确认与`GITHUB_TOKEN`关联的账户确实有访问权限。

3. **网络和防火墙设置**：如果您的环境在受限的网络中，请检查网络和防火墙设置，确保不会阻止对GitHub的访问。

4. **代码审查**：复查代码中与`GITHUB_TOKEN`相关的部分，确保令牌被正确设置在HTTP请求的`Authorization`头部。

5. **Token更新**：如果令牌近期有过更改，请确保您使用的是最新的`GITHUB_TOKEN`。

应用以上建议，应能解决访问私有仓库的权限问题。如果仍存在问题，请继续探索或提供更多的错误信息。

**Comment by ClawDevin** [comment]
**具体的实施方案**:

进一步地，修复访问私有仓库的问题需要关注`gh_interacter/gh_interacter.py`文件中的代码。在该文件中，GitHub API的请求被用于获取Pull Request内容、文件内容、Issue信息等，这些请求需要正确地使用`GITHUB_TOKEN`进行授权。

**建议修改**:
1. 在`gh_interacter/gh_interacter.py`中，确保发送给GitHub API的所有请求都包含了正确的`Authorization`头。例如，修改任何使用`requests`库发起的请求，确保它们包含如下的头部设置：
```python
headers = {'Authorization': f'token {os.environ.get("GITHUB_TOKEN")}'}
response = requests.get(url, headers=headers)
```

2. 确保环境变量`GITHUB_TOKEN`在运行时是可用的，并且包含有权访问私有仓库的GitHub访问令牌。

通过这些修改，请求应该能够被私有仓库正确地授权和接收。如果您在修改这些部分代码后仍然遇到问题，请确保令牌权限配置正确，并且令牌没有过期或被撤销。

**Comment by ClawDevin** [comment]
针对`get_pr_content()`函数中与GitHub API认证相关的问题，我有一些建议来确保正确的认证并解决权限问题。该函数中向GitHub发起的请求包括获取Pull Request基本信息和获取Pull Request的diff信息，都需要正确附带`Authorization`头部以使用`GITHUB_TOKEN`进行认证。

**具体的修改意见如下**：

1. **获取Pull Request基本信息**时，修改请求如下：
```python
github_api_url = f"https://api.github.com/repos/{repo_full_name}/pulls/{pr_number}"
headers = {'Authorization': f'token {os.environ.get("GITHUB_TOKEN")}'}
response = requests.get(github_api_url, headers=headers)
```

通过添加`Authorization`头部来包含`GITHUB_TOKEN`，确保请求能够通过认证。

2. **获取Pull Request的diff信息**时，同样需要添加`Authorization`头部，修改请求如下：
```python
diff_response = requests.get(diff_url, headers={'Accept': 'application/vnd.github.v3.diff', 'Authorization': f'token {os.environ.get("GITHUB_TOKEN")}'})
```

这样修改后，两个请求都将包括适当的`Authorization`头部，使用`GITHUB_TOKEN`进行认证，有助于解决因权限问题导致的访问限制。

应用这些修改应能解决提到的认证问题，使得函数能够正确访问GitHub API所需的资源。
